// Inlines Leaflet into a TS module so the walk map works without loading scripts from the internet.
const fs = require("fs");
const js = fs.readFileSync(require.resolve("leaflet/dist/leaflet.js"), "utf8");
const css = fs.readFileSync(require.resolve("leaflet/dist/leaflet.css"), "utf8");
fs.writeFileSync(
  __dirname + "/../src/components/leafletAsset.ts",
  "// Generated by scripts/gen-leaflet.js — do not edit.\n" +
    `export const LEAFLET_JS = ${JSON.stringify(js)};\nexport const LEAFLET_CSS = ${JSON.stringify(css)};\n`,
);
